# Generated by Django 3.2.8 on 2021-10-27 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valetapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValetService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valetType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carReg', models.DecimalField(decimal_places=15, max_digits=20)),
                ('valetservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valetapp.valetservice')),
            ],
        ),
    ]
