# Generated by Django 3.2.8 on 2021-11-03 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valetapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='location',
        ),
        migrations.AddField(
            model_name='customer',
            name='membershipType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='valetapp.membershiptype'),
        ),
    ]
