# Generated by Django 3.2.8 on 2021-11-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valetapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershiptype',
            name='discount',
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
