# Generated by Django 3.2.8 on 2021-11-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valetapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_state',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='carReg',
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
