# Generated by Django 3.2.8 on 2021-11-04 17:49

from django.db import migrations, models
import valetapp.models.booking


class Migration(migrations.Migration):

    dependencies = [
        ('valetapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_state',
            field=models.CharField(choices=[('PENDING', 'pending'), ('BOOKED', 'booked'), ('CANCELLED', 'cancelled'), ('END_TIME', 'endtime')], default=valetapp.models.booking.BookingStates['PENDING'], max_length=20),
        ),
    ]
