# Generated by Django 3.2.8 on 2021-11-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valetapp', '0002_alter_booking_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
