# Generated by Django 3.2.8 on 2021-11-09 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valetapp', '0002_booking_booking_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='valetservice',
        ),
        migrations.DeleteModel(
            name='ValetService',
        ),
    ]
