# Generated by Django 3.2.8 on 2021-11-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valetapp', '0003_auto_20211102_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
