# Generated by Django 3.2.8 on 2021-11-20 14:19

from django.db import migrations, models
import valetapp.models.booking


class Migration(migrations.Migration):

    dependencies = [
        ('valetapp', '0005_alter_booking_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_state',
            field=models.CharField(choices=[('PENDING', 'pending'), ('BOOKED', 'booked'), ('CANCELLED', 'cancelled')], default=valetapp.models.booking.BookingStates['PENDING'], max_length=20),
        ),
    ]
